services:
  postgres:
    image: postgres:15-alpine
    container_name: minibilling2024-postgre
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '${POSTGRE_PORT}:5432'
    volumes:
      - .postgre_db:/var/lib/postgresql/data
volumes:
  .postgre_db: